### ISSUE TITLE
add bookmarks

### ISSUE THREAD

**Issue by MahmoudHamdy02** [KKoukiou/cockpit-navigator#100]
This was inspired by the 'Star' icon in the mockups. 
![star](https://github.com/KKoukiou/cockpit-navigator/assets/14921356/7e3492c8-ac62-4f66-a9bd-ca54769b9337)

**Comment by KKoukiou** [comment]
This feature does not exist in the two 2 file managers I just checked (midnight commander and nautilus) so I think it's fine to skip till some user requests it in the future.
