### ISSUE TITLE
Edit file/folder properties

### ISSUE THREAD

**Issue by KKoukiou** [KKoukiou/cockpit-navigator#30]
* [ ] Edit owner
* [ ] Edit group
* [ ] Edit permissions

Old implementation: 
![Screen Shot 2023-05-19 at 13 56 11](https://github.com/KKoukiou/cockpit-navigator/assets/14921356/006e0ea2-ea75-4bde-9b70-9cbfb22f9f19)

**Comment by garrett** [comment]
I'm working on a mockup right now.

Checkboxes only work for an indicated state change. Switches are for active state changes ("active apply"). Sidebars can only have active apply. Modals exist to allow for indicating intent and then applying that intent with an action like "save".

This design from the old navigator app doesn't work for these reasons:

- It's not clear if it is a sidebar or modal. Given that it has cancel and save buttons (I think?), it's supposed to be a modal?
- It doesn't follow PF guidelines.
- Buttons should have text, not icons.
- Buttons should be left-aligned in modals, not right aligned.
- Floppy icons should not be used.
- Red is for a dangerous action, such as delete. Is this delete? I think it's supposed to be cancel, which is the opposite of a dangerous action. (It's short for "Do not do an action, even if I changed something in this dialog.")
- Checkboxes are not labeled (or they have two labels in a table, which would need proper accessibility, with a `scope="row"` and `scope="col"` for each `th`).
- What's "unchanged"? Does it change if you change things below it? That would violate the standard Z-order heiarchy of UI action. https://vanseodesign.com/web-design/3-design-layouts/ (Basically: Things that come first across zig-zagging Zs affect things that come later, not the other way around. Left first, then right, then left again below that, then right again below that, and so on.)

The solution isn't as simple as it appears. Would we want to have active changes in the sidebar? If so, they would _immediately_ apply with a switch and we couldn't do sub-folder permission changes in a similar UI. If it's a dialog, then they're queued up and we could change the permissions on an individual file or directory as well as recursively (files and directories inside a directory).

---

## So, if modal, then

We could group each by owner and either use a divider or spacing (another way of grouping):

![image](https://github.com/KKoukiou/cockpit-navigator/assets/10246/4ec2cd16-7474-42be-9324-44d0be52df60)

Another approach would be to split the width in half and group the owner/group names alongside the permissions:

![image](https://github.com/KKoukiou/cockpit-navigator/assets/10246/eaea8686-872a-40bf-a965-3927e6d62c96)

Yet another approach would be to group the editable fields (owner/group) and the permissions after, with a divider:

![image](https://github.com/KKoukiou/cockpit-navigator/assets/10246/28b41738-a224-4cfa-a3cc-5f8a89a6e812)

(All of the above mockups show the actions for a folder. A file would just have "Change" and "Cancel".)

And the sidebar would have to show some content, kinda like this:

![Navigator, with inline breadcrumbs (1)](https://github.com/KKoukiou/cockpit-navigator/assets/10246/05893aef-1311-4aed-b864-9a2fad3e5a90)

![Navigator, with inline breadcrumbs](https://github.com/KKoukiou/cockpit-navigator/assets/10246/420ab476-688e-40fe-969b-6b70ec8279ab)

---

Anyway, this is all a work in progress (and is subject to change), but I wanted to share _something_ to elaborate why the old screen wouldn't work, and show what we might want to do instead. It's basically end of my work day today and I didn't want to forget about sharing what I have been working on.

**Comment by garrett** [comment]
How's this? It's functionally the same as the last mockup, except:

- it uses subheadings for the sections instead of a divider 
- the user and group are dropdowns to select available ones on the system (perhaps group should change to the default of the user when the user is changed?)

![File properties and access](https://github.com/KKoukiou/cockpit-navigator/assets/10246/d47eb180-f8d0-46aa-b4a3-4c8bc35681bc)

![Directory properties and access](https://github.com/KKoukiou/cockpit-navigator/assets/10246/7b3cfe2d-3ab0-4bba-8cbd-013a642acea4)

**Comment by garrett** [comment]
BTW: The suggestion about changing the group when the user changes should only happen if the user is not part of that group.
