### ISSUE TITLE
Sort directories before files

### ISSUE THREAD

**Issue by garrett** [KKoukiou/cockpit-navigator#58]
Directories should be sorted before files. Each set should have the selected sorting (alphanumeric by default, but remembering the last selected state via localstorage) applied relative to the set (of directories or folders).

For example, here's a mockup with the folders sorted before the files:

![Navigator, with inline breadcrumbs (1)](https://github.com/KKoukiou/cockpit-navigator/assets/10246/3b499d62-5801-4b30-981d-529b113e24b6)

**Comment by KKoukiou** [comment]
@garrett hmm that's not how nautilus works. That's how midnight commander works, so I guess we are not diverging from everything.
